### ISSUE TITLE
Why using customized EvolveTODO.Helpers.EntityData?

### ISSUE THREAD

**Issue by mizhou2011** [MikeCodesDotNet/Evolve-TODO-App#3]
Hello Mike, I couldn't reproduce the example you demonstrated in Evolve 16 (https://www.youtube.com/watch?v=cvVuREnVZk8). Specifically, I couldn't make my code consume the Azure data.
I found you used a customized EvolveTODO.Helpers.EntityData. And you used a property called AzureVersion, Does this have special consideration? 
However, the backend code (https://github.com/adrianhall/xamarin-evolve-demo) provided by Adrian just used the default EntityData from Microsoft.Azure.Mobile.Server. Was this the problem why my codes didn't work?

**Comment by adrianhall** [comment]
The customized EntityData still provides a version field - we just called it something different.  Also, the customized EntityData doesn't depend on ITableData, nor does it have a Deleted field (that is handled by the Azure Client SDK).  You definitely want to tack on these fields (with the JsonProperty tags) for your client objects.
